# config/pipeline.yaml

# 1. Where your raw sequencing reads live
reads_dir: "/Volumes/Alessia_4T/ALPFU_plates/raw_reads"

# 2. Taxonomy spreadsheet (Excel .xlsx or .csv BOLD format)
taxonomy_file: "/Users/utente/Desktop/PhD/BGE_ALPFUNGI/BOLD_ALPFU_Taxonomy.xlsx"
taxonomy_sheet: "Taxonomy" #Taxonomy sheet of the spreadsheet

# 3. Reference database (FASTA of SSU, ITS, LSU sequences) # ref_fasta is auto-downloaded if unset
ref_fasta: ""

# 4. Trimming
skip_trimming: false # if true, will *NOT* run fastp but use the input fastq

# 5. Mapping quality threshold and coverage check
auto_subsample: true # Enable automatic coverage management
# Uncomment to use custom thresholds (triggers slower per-base mode)
# WARNING: Custom values enable per-base subsampling (slower but more precise)
#max_coverage: 300         # More aggressive: subsample if coverage > 300×  
#target_coverage: 100      # More aggressive: reduce to 100×
mapq: 0 # minimum mapping quality (default: 0)

# 6. Soft-clipped read filtering
filter_softclipped_reads: true # set to true to filter reads with soft-clipped bases
softclip_filter_mode: full # full = remove entire read, trim = remove softclip only

# 7. Assembler
assembler: spades # change to "spades" to run SPAdes, or "megahit" to run MEGAHIT

# 8. Computational resources
threads: 16 # e.g. number of CPU cores to use
mem_gb: 32 # e.g. total RAM in GB

# 9. Where to put all output
outdir: "results"

# 10. Phylogenetic analysis
skip_phylogeny: true # if true, skip IQ-TREE phylogenetic inference
